apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: github-tests-java-quarkus-rrbzusvt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-tests-java-quarkus-rrbzusvt 
  name: github-tests-java-quarkus-rrbzusvt
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: github-tests-java-quarkus-rrbzusvt 
